const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');

test('global index merges legacy aliases once, retains invalid paths and safely relocates/removes', async t => {
  const { Projects } = await import('../electron/projects.ts');
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'graphtraj-index-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const first = path.join(root, 'first');
  const second = path.join(root, 'second');
  const absent = path.join(root, 'missing');
  await fs.mkdir(first); await fs.mkdir(second);
  await fs.writeFile(path.join(first, 'keep.txt'), 'project content');
  const alias = path.join(root, 'alias');
  await fs.symlink(first, alias);
  const file = path.join(root, 'home/.graphtraj/projects.json');
  const legacy = path.join(root, 'userData/projects.json');
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.mkdir(path.dirname(legacy), { recursive: true });
  await fs.writeFile(file, JSON.stringify({ projects: [{ id: 'a', root: first }], selected: 'a' }));
  const original = JSON.stringify({ projects: [{ id: 'duplicate', root: alias },
    { id: 'b', root: second }, { id: 'missing', root: absent }], selected: 'b' });
  await fs.writeFile(legacy, original);
  const reader = { read: async folder => { await fs.access(folder); return { tickets: [] }; } };
  const index = new Projects(file, reader, legacy);
  t.after(() => index.close());
  await index.load();
  assert.equal(index.list().projects.length, 3);
  assert.equal(index.list().selected, 'a');
  assert.match(index.list().projects.find(p => p.id === 'missing').unavailable, /ENOENT/);
  assert.equal(await fs.readFile(legacy, 'utf8'), original);
  await assert.rejects(index.relocate('missing', 'relative'), /absolute/);
  await assert.rejects(index.relocate('missing', absent), /ENOENT/);
  await index.select('missing');
  await index.relocate('missing', second);
  assert.equal(index.list().projects.length, 2);
  assert.equal(index.list().selected, 'b');
  const moved = path.join(root, 'moved');
  await fs.rename(first, moved);
  await index.refreshAvailability();
  assert.match(index.list().projects[0].unavailable, /ENOENT/);
  await index.relocate('a', moved);
  assert.equal(index.list().projects[0].id, 'a');
  assert.equal(index.list().projects[0].unavailable, undefined);
  await index.remove('a');
  assert.equal(await fs.readFile(path.join(moved, 'keep.txt'), 'utf8'), 'project content');
  const reopened = new Projects(file, reader, legacy);
  t.after(() => reopened.close());
  await reopened.load();
  assert.deepEqual(reopened.list(), index.list(), 'legacy must not resurrect removed entries');
  assert.equal(await fs.readFile(legacy, 'utf8'), original);
});

test('first migration preserves selection and malformed legacy/global files are never overwritten', async t => {
  const { Projects } = await import('../electron/projects.ts');
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'graphtraj-migration-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const file = path.join(root, '.graphtraj/projects.json');
  const legacy = path.join(root, 'legacy.json');
  const original = JSON.stringify({ projects: [{ id: 'chosen', root }], selected: 'chosen' });
  await fs.writeFile(legacy, original);
  const reader = { read: async () => ({ tickets: [] }) };
  const index = new Projects(file, reader, legacy);
  t.after(() => index.close());
  await index.load();
  assert.equal(index.list().selected, 'chosen');
  assert.equal(await fs.readFile(legacy, 'utf8'), original);
  await fs.writeFile(file, '{broken');
  await assert.rejects(new Projects(file, reader, legacy).load(), SyntaxError);
  assert.equal(await fs.readFile(file, 'utf8'), '{broken');
  await fs.rm(file);
  await fs.writeFile(legacy, '{broken legacy');
  await assert.rejects(new Projects(file, reader, legacy).load(), SyntaxError);
  assert.equal(await fs.readFile(legacy, 'utf8'), '{broken legacy');
  await assert.rejects(fs.access(file), /ENOENT/);
});
